# Generated by Django 5.2.1 on 2025-06-27 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=122)),
                ('dob', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('occupation', models.CharField(max_length=200)),
                ('gname', models.CharField(max_length=122)),
                ('goccupation', models.CharField(max_length=200)),
                ('gcontact', models.CharField(max_length=15)),
                ('subjects_interested', models.CharField(max_length=300)),
                ('reference_sources', models.CharField(help_text='e.g. Teachers, Friends, Relatives', max_length=200)),
                ('reference_name', models.CharField(blank=True, max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('course', models.CharField(max_length=122)),
                ('semester', models.CharField(max_length=122)),
                ('complaint', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=200)),
                ('class_semester', models.CharField(max_length=100)),
                ('stream', models.CharField(max_length=100)),
                ('passing_year', models.CharField(max_length=10)),
                ('percentage', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='home.admission')),
            ],
        ),
    ]
