# Generated by Django 5.2.1 on 2025-06-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='gcontact',
            new_name='guardian_contact',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='goccupation',
            new_name='references',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='gname',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='reference_name',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='reference_sources',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='subjects_interested',
        ),
        migrations.AddField(
            model_name='admission',
            name='class_sem1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='class_sem2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='class_sem3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='guardian_name',
            field=models.CharField(default='2000-01-01', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='guardian_occupation',
            field=models.CharField(default='Not Provided', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='institute1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='institute2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='institute3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='mail',
            field=models.EmailField(default='example@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='passing_year1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='passing_year2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='passing_year3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='percentage1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='percentage2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='percentage3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='refname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='stream1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='stream2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='stream3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='subjects',
            field=models.CharField(default='not provided', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='admission',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='admission',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='admission',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='admission',
            name='occupation',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
    ]
